### PR TITLE
update kubevirt libvirt-src template

### PR DESCRIPTION
**Pull request by sallyom**
@dhiller this is where I got to today

The kubevirt tests have to run on the gcp host, rather than in an OpenShift pod.  In the template I added  a step to copy over the kubevirt repo to the gcp instance (i think, it's running now so hopefully it works). Also, the tests require that docker is installed, from what I gather.  
I shared the error I'm seeing in slack, we'll sync up tomorrow - at this point you'll probably be better to debug than me, since I know very little about kubevirt :) Glad I've picked up this much, though!

### CODE REVIEW

**Comment by sallyom** [comment]
also, with TEST_COMMAND, ~I kept the same as what installer job is running for their libvirt-e2e - since I'm assuming the tests listed there are 'known-good' in the nested virt cluster.~ i'm only running the kubevirt-tests, and I've added your test script in the template, you'll see.

**Comment by sallyom** [comment]
oh shooooot I just copied the wrong file, have to reconstruct my template changes... booooo I'll repush this by tomorrow

**Comment by sallyom** [comment]
oh great, this is working nicely! Here's the error now, it's when running `kubevirt-tests.sh`:
```
cd /home/packer/kubevirt/tools/manifest-templator/
--
  | + go build
go: finding golang.org/x/text v0.0.0-20160726164857-2910a502d2bf
--
  | go: bitbucket.org/ww/goautoneg@v0.0.0-20120707110453-75cd24fc2f2c: hg clone -U https://bitbucket.org/ww/goautoneg  . in /root/go/pkg/mod/cache/vcs/59c2185b80ea440a7c3b8c5eff3d8abb68c53dea1f20f615370c924c4150b27f: exec: "hg": executable file not found in $PATH
  | go: finding github.com/modern-go/reflect2 v0.0.0-20180320133207-05fbef0ca5da
go: error loading module requirements
```
Looks like it's failing to build this: https://github.com/kubevirt/kubevirt/tree/master/tools/manifest-templator  here: https://github.com/kubevirt/kubevirt/blob/master/hack/build-manifests.sh#L36

I suggest cherry-picking this commit  or merging this PR into your PR, then fix from there.  
Also, request gce creds so you can debug in the gce instance when running this :)

**Comment by dhiller** [comment]
Hey @sallyom thanks for your great work, this is appreciated very much. Sorry I'm responding so late, will continue to work on this again now. Maybe I still need to bother you again when trying to debug on gcp.

**Comment by dhiller** [comment]
> oh great, this is working nicely! Here's the error now, it's when running `kubevirt-tests.sh`:
> 
> ```
> cd /home/packer/kubevirt/tools/manifest-templator/
> --
>   | + go build
> go: finding golang.org/x/text v0.0.0-20160726164857-2910a502d2bf
> --
>   | go: bitbucket.org/ww/goautoneg@v0.0.0-20120707110453-75cd24fc2f2c: hg clone -U https://bitbucket.org/ww/goautoneg  . in /root/go/pkg/mod/cache/vcs/59c2185b80ea440a7c3b8c5eff3d8abb68c53dea1f20f615370c924c4150b27f: exec: "hg": executable file not found in $PATH
>   | go: finding github.com/modern-go/reflect2 v0.0.0-20180320133207-05fbef0ca5da
> go: error loading module requirements
> ```
Interesting, I didn't encounter this when building from within the built src image. Maybe there's some path issue prohibiting to find the vendored dependencies? However, thanks again!

**Pull request merged**
